<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RiverSight.Domain\RiverSight.Domain.csproj" />
    <ProjectReference Include="..\RiverSight.Infrastructure.Vision\RiverSight.Infrastructure.Vision.csproj" />
  </ItemGroup>

</Project>
